// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.adtiming.om.pb;

public final class CommonPB {
  private CommonPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Plat}
   */
  public enum Plat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>iOS = 0;</code>
     */
    iOS(0),
    /**
     * <code>Android = 1;</code>
     */
    Android(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>iOS = 0;</code>
     */
    public static final int iOS_VALUE = 0;
    /**
     * <code>Android = 1;</code>
     */
    public static final int Android_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Plat valueOf(int value) {
      return forNumber(value);
    }

    public static Plat forNumber(int value) {
      switch (value) {
        case 0: return iOS;
        case 1: return Android;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Plat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Plat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Plat>() {
            public Plat findValueByNumber(int number) {
              return Plat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.adtiming.om.pb.CommonPB.getDescriptor().getEnumTypes().get(0);
    }

    private static final Plat[] VALUES = values();

    public static Plat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Plat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Plat)
  }

  /**
   * Protobuf enum {@code AdType}
   */
  public enum AdType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 横幅
     * </pre>
     *
     * <code>Banner = 0;</code>
     */
    Banner(0),
    /**
     * <pre>
     * 原生
     * </pre>
     *
     * <code>Native = 1;</code>
     */
    Native(1),
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>RewardVideo = 2;</code>
     */
    RewardVideo(2),
    /**
     * <pre>
     * 插屏
     * </pre>
     *
     * <code>Interstitial = 3;</code>
     */
    Interstitial(3),
    /**
     * <pre>
     * 开屏
     * </pre>
     *
     * <code>Splash = 4;</code>
     */
    Splash(4),
    /**
     * <pre>
     * 交叉推广
     * </pre>
     *
     * <code>CrossPromotion = 5;</code>
     */
    CrossPromotion(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 横幅
     * </pre>
     *
     * <code>Banner = 0;</code>
     */
    public static final int Banner_VALUE = 0;
    /**
     * <pre>
     * 原生
     * </pre>
     *
     * <code>Native = 1;</code>
     */
    public static final int Native_VALUE = 1;
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>RewardVideo = 2;</code>
     */
    public static final int RewardVideo_VALUE = 2;
    /**
     * <pre>
     * 插屏
     * </pre>
     *
     * <code>Interstitial = 3;</code>
     */
    public static final int Interstitial_VALUE = 3;
    /**
     * <pre>
     * 开屏
     * </pre>
     *
     * <code>Splash = 4;</code>
     */
    public static final int Splash_VALUE = 4;
    /**
     * <pre>
     * 交叉推广
     * </pre>
     *
     * <code>CrossPromotion = 5;</code>
     */
    public static final int CrossPromotion_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AdType valueOf(int value) {
      return forNumber(value);
    }

    public static AdType forNumber(int value) {
      switch (value) {
        case 0: return Banner;
        case 1: return Native;
        case 2: return RewardVideo;
        case 3: return Interstitial;
        case 4: return Splash;
        case 5: return CrossPromotion;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AdType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AdType>() {
            public AdType findValueByNumber(int number) {
              return AdType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.adtiming.om.pb.CommonPB.getDescriptor().getEnumTypes().get(1);
    }

    private static final AdType[] VALUES = values();

    public static AdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AdType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AdType)
  }

  /**
   * Protobuf enum {@code ABTest}
   */
  public enum ABTest
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>None = 0;</code>
     */
    None(0),
    /**
     * <code>A = 1;</code>
     */
    A(1),
    /**
     * <code>B = 2;</code>
     */
    B(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>None = 0;</code>
     */
    public static final int None_VALUE = 0;
    /**
     * <code>A = 1;</code>
     */
    public static final int A_VALUE = 1;
    /**
     * <code>B = 2;</code>
     */
    public static final int B_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ABTest valueOf(int value) {
      return forNumber(value);
    }

    public static ABTest forNumber(int value) {
      switch (value) {
        case 0: return None;
        case 1: return A;
        case 2: return B;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ABTest>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ABTest> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ABTest>() {
            public ABTest findValueByNumber(int number) {
              return ABTest.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.adtiming.om.pb.CommonPB.getDescriptor().getEnumTypes().get(2);
    }

    private static final ABTest[] VALUES = values();

    public static ABTest valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ABTest(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ABTest)
  }

  public interface CountryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Country)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string a2 = 1;</code>
     */
    java.lang.String getA2();
    /**
     * <code>optional string a2 = 1;</code>
     */
    com.google.protobuf.ByteString
        getA2Bytes();

    /**
     * <code>optional string a3 = 2;</code>
     */
    java.lang.String getA3();
    /**
     * <code>optional string a3 = 2;</code>
     */
    com.google.protobuf.ByteString
        getA3Bytes();

    /**
     * <code>optional int32 tz = 3;</code>
     */
    int getTz();

    /**
     * <code>optional int32 dcenter = 4;</code>
     */
    int getDcenter();
  }
  /**
   * Protobuf type {@code Country}
   */
  public  static final class Country extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Country)
      CountryOrBuilder {
    // Use Country.newBuilder() to construct.
    private Country(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Country() {
      a2_ = "";
      a3_ = "";
      tz_ = 0;
      dcenter_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Country(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              a2_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              a3_ = s;
              break;
            }
            case 24: {

              tz_ = input.readInt32();
              break;
            }
            case 32: {

              dcenter_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adtiming.om.pb.CommonPB.internal_static_Country_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adtiming.om.pb.CommonPB.internal_static_Country_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adtiming.om.pb.CommonPB.Country.class, com.adtiming.om.pb.CommonPB.Country.Builder.class);
    }

    public static final int A2_FIELD_NUMBER = 1;
    private volatile java.lang.Object a2_;
    /**
     * <code>optional string a2 = 1;</code>
     */
    public java.lang.String getA2() {
      java.lang.Object ref = a2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a2_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a2 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getA2Bytes() {
      java.lang.Object ref = a2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int A3_FIELD_NUMBER = 2;
    private volatile java.lang.Object a3_;
    /**
     * <code>optional string a3 = 2;</code>
     */
    public java.lang.String getA3() {
      java.lang.Object ref = a3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a3_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a3 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getA3Bytes() {
      java.lang.Object ref = a3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TZ_FIELD_NUMBER = 3;
    private int tz_;
    /**
     * <code>optional int32 tz = 3;</code>
     */
    public int getTz() {
      return tz_;
    }

    public static final int DCENTER_FIELD_NUMBER = 4;
    private int dcenter_;
    /**
     * <code>optional int32 dcenter = 4;</code>
     */
    public int getDcenter() {
      return dcenter_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getA2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a2_);
      }
      if (!getA3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, a3_);
      }
      if (tz_ != 0) {
        output.writeInt32(3, tz_);
      }
      if (dcenter_ != 0) {
        output.writeInt32(4, dcenter_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getA2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a2_);
      }
      if (!getA3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, a3_);
      }
      if (tz_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, tz_);
      }
      if (dcenter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dcenter_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adtiming.om.pb.CommonPB.Country)) {
        return super.equals(obj);
      }
      com.adtiming.om.pb.CommonPB.Country other = (com.adtiming.om.pb.CommonPB.Country) obj;

      boolean result = true;
      result = result && getA2()
          .equals(other.getA2());
      result = result && getA3()
          .equals(other.getA3());
      result = result && (getTz()
          == other.getTz());
      result = result && (getDcenter()
          == other.getDcenter());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + A2_FIELD_NUMBER;
      hash = (53 * hash) + getA2().hashCode();
      hash = (37 * hash) + A3_FIELD_NUMBER;
      hash = (53 * hash) + getA3().hashCode();
      hash = (37 * hash) + TZ_FIELD_NUMBER;
      hash = (53 * hash) + getTz();
      hash = (37 * hash) + DCENTER_FIELD_NUMBER;
      hash = (53 * hash) + getDcenter();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adtiming.om.pb.CommonPB.Country parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Country parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adtiming.om.pb.CommonPB.Country prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Country}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Country)
        com.adtiming.om.pb.CommonPB.CountryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adtiming.om.pb.CommonPB.internal_static_Country_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adtiming.om.pb.CommonPB.internal_static_Country_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adtiming.om.pb.CommonPB.Country.class, com.adtiming.om.pb.CommonPB.Country.Builder.class);
      }

      // Construct using com.adtiming.om.pb.CommonPB.Country.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a2_ = "";

        a3_ = "";

        tz_ = 0;

        dcenter_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adtiming.om.pb.CommonPB.internal_static_Country_descriptor;
      }

      public com.adtiming.om.pb.CommonPB.Country getDefaultInstanceForType() {
        return com.adtiming.om.pb.CommonPB.Country.getDefaultInstance();
      }

      public com.adtiming.om.pb.CommonPB.Country build() {
        com.adtiming.om.pb.CommonPB.Country result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.adtiming.om.pb.CommonPB.Country buildPartial() {
        com.adtiming.om.pb.CommonPB.Country result = new com.adtiming.om.pb.CommonPB.Country(this);
        result.a2_ = a2_;
        result.a3_ = a3_;
        result.tz_ = tz_;
        result.dcenter_ = dcenter_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adtiming.om.pb.CommonPB.Country) {
          return mergeFrom((com.adtiming.om.pb.CommonPB.Country)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adtiming.om.pb.CommonPB.Country other) {
        if (other == com.adtiming.om.pb.CommonPB.Country.getDefaultInstance()) return this;
        if (!other.getA2().isEmpty()) {
          a2_ = other.a2_;
          onChanged();
        }
        if (!other.getA3().isEmpty()) {
          a3_ = other.a3_;
          onChanged();
        }
        if (other.getTz() != 0) {
          setTz(other.getTz());
        }
        if (other.getDcenter() != 0) {
          setDcenter(other.getDcenter());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adtiming.om.pb.CommonPB.Country parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adtiming.om.pb.CommonPB.Country) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object a2_ = "";
      /**
       * <code>optional string a2 = 1;</code>
       */
      public java.lang.String getA2() {
        java.lang.Object ref = a2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getA2Bytes() {
        java.lang.Object ref = a2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public Builder setA2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public Builder clearA2() {
        
        a2_ = getDefaultInstance().getA2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public Builder setA2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object a3_ = "";
      /**
       * <code>optional string a3 = 2;</code>
       */
      public java.lang.String getA3() {
        java.lang.Object ref = a3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a3 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getA3Bytes() {
        java.lang.Object ref = a3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a3 = 2;</code>
       */
      public Builder setA3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a3 = 2;</code>
       */
      public Builder clearA3() {
        
        a3_ = getDefaultInstance().getA3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a3 = 2;</code>
       */
      public Builder setA3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a3_ = value;
        onChanged();
        return this;
      }

      private int tz_ ;
      /**
       * <code>optional int32 tz = 3;</code>
       */
      public int getTz() {
        return tz_;
      }
      /**
       * <code>optional int32 tz = 3;</code>
       */
      public Builder setTz(int value) {
        
        tz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tz = 3;</code>
       */
      public Builder clearTz() {
        
        tz_ = 0;
        onChanged();
        return this;
      }

      private int dcenter_ ;
      /**
       * <code>optional int32 dcenter = 4;</code>
       */
      public int getDcenter() {
        return dcenter_;
      }
      /**
       * <code>optional int32 dcenter = 4;</code>
       */
      public Builder setDcenter(int value) {
        
        dcenter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dcenter = 4;</code>
       */
      public Builder clearDcenter() {
        
        dcenter_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Country)
    }

    // @@protoc_insertion_point(class_scope:Country)
    private static final com.adtiming.om.pb.CommonPB.Country DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adtiming.om.pb.CommonPB.Country();
    }

    public static com.adtiming.om.pb.CommonPB.Country getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Country>
        PARSER = new com.google.protobuf.AbstractParser<Country>() {
      public Country parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Country(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Country> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Country> getParserForType() {
      return PARSER;
    }

    public com.adtiming.om.pb.CommonPB.Country getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DictOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dict)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 pid = 2;</code>
     */
    int getPid();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string value = 4;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 4;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code Dict}
   */
  public  static final class Dict extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dict)
      DictOrBuilder {
    // Use Dict.newBuilder() to construct.
    private Dict(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dict() {
      id_ = 0;
      pid_ = 0;
      name_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Dict(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              pid_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adtiming.om.pb.CommonPB.internal_static_Dict_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adtiming.om.pb.CommonPB.internal_static_Dict_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adtiming.om.pb.CommonPB.Dict.class, com.adtiming.om.pb.CommonPB.Dict.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PID_FIELD_NUMBER = 2;
    private int pid_;
    /**
     * <code>optional int32 pid = 2;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 4;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>optional string value = 4;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (pid_ != 0) {
        output.writeInt32(2, pid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adtiming.om.pb.CommonPB.Dict)) {
        return super.equals(obj);
      }
      com.adtiming.om.pb.CommonPB.Dict other = (com.adtiming.om.pb.CommonPB.Dict) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getPid()
          == other.getPid());
      result = result && getName()
          .equals(other.getName());
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Dict parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adtiming.om.pb.CommonPB.Dict prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dict}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dict)
        com.adtiming.om.pb.CommonPB.DictOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adtiming.om.pb.CommonPB.internal_static_Dict_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adtiming.om.pb.CommonPB.internal_static_Dict_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adtiming.om.pb.CommonPB.Dict.class, com.adtiming.om.pb.CommonPB.Dict.Builder.class);
      }

      // Construct using com.adtiming.om.pb.CommonPB.Dict.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        pid_ = 0;

        name_ = "";

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adtiming.om.pb.CommonPB.internal_static_Dict_descriptor;
      }

      public com.adtiming.om.pb.CommonPB.Dict getDefaultInstanceForType() {
        return com.adtiming.om.pb.CommonPB.Dict.getDefaultInstance();
      }

      public com.adtiming.om.pb.CommonPB.Dict build() {
        com.adtiming.om.pb.CommonPB.Dict result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.adtiming.om.pb.CommonPB.Dict buildPartial() {
        com.adtiming.om.pb.CommonPB.Dict result = new com.adtiming.om.pb.CommonPB.Dict(this);
        result.id_ = id_;
        result.pid_ = pid_;
        result.name_ = name_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adtiming.om.pb.CommonPB.Dict) {
          return mergeFrom((com.adtiming.om.pb.CommonPB.Dict)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adtiming.om.pb.CommonPB.Dict other) {
        if (other == com.adtiming.om.pb.CommonPB.Dict.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adtiming.om.pb.CommonPB.Dict parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adtiming.om.pb.CommonPB.Dict) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 2;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 4;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 4;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 4;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 4;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 4;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Dict)
    }

    // @@protoc_insertion_point(class_scope:Dict)
    private static final com.adtiming.om.pb.CommonPB.Dict DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adtiming.om.pb.CommonPB.Dict();
    }

    public static com.adtiming.om.pb.CommonPB.Dict getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dict>
        PARSER = new com.google.protobuf.AbstractParser<Dict>() {
      public Dict parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Dict(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dict> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dict> getParserForType() {
      return PARSER;
    }

    public com.adtiming.om.pb.CommonPB.Dict getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CurrencyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Currency)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *原币种
     * </pre>
     *
     * <code>optional string cur_from = 1;</code>
     */
    java.lang.String getCurFrom();
    /**
     * <pre>
     *原币种
     * </pre>
     *
     * <code>optional string cur_from = 1;</code>
     */
    com.google.protobuf.ByteString
        getCurFromBytes();

    /**
     * <pre>
     *需要转换为的币种
     * </pre>
     *
     * <code>optional string cur_to = 2;</code>
     */
    java.lang.String getCurTo();
    /**
     * <pre>
     *需要转换为的币种
     * </pre>
     *
     * <code>optional string cur_to = 2;</code>
     */
    com.google.protobuf.ByteString
        getCurToBytes();

    /**
     * <pre>
     *汇率
     * </pre>
     *
     * <code>optional float exchange_rate = 3;</code>
     */
    float getExchangeRate();
  }
  /**
   * Protobuf type {@code Currency}
   */
  public  static final class Currency extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Currency)
      CurrencyOrBuilder {
    // Use Currency.newBuilder() to construct.
    private Currency(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Currency() {
      curFrom_ = "";
      curTo_ = "";
      exchangeRate_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Currency(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              curFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              curTo_ = s;
              break;
            }
            case 29: {

              exchangeRate_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adtiming.om.pb.CommonPB.internal_static_Currency_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adtiming.om.pb.CommonPB.internal_static_Currency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adtiming.om.pb.CommonPB.Currency.class, com.adtiming.om.pb.CommonPB.Currency.Builder.class);
    }

    public static final int CUR_FROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object curFrom_;
    /**
     * <pre>
     *原币种
     * </pre>
     *
     * <code>optional string cur_from = 1;</code>
     */
    public java.lang.String getCurFrom() {
      java.lang.Object ref = curFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        curFrom_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *原币种
     * </pre>
     *
     * <code>optional string cur_from = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurFromBytes() {
      java.lang.Object ref = curFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        curFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUR_TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object curTo_;
    /**
     * <pre>
     *需要转换为的币种
     * </pre>
     *
     * <code>optional string cur_to = 2;</code>
     */
    public java.lang.String getCurTo() {
      java.lang.Object ref = curTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        curTo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *需要转换为的币种
     * </pre>
     *
     * <code>optional string cur_to = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCurToBytes() {
      java.lang.Object ref = curTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        curTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGE_RATE_FIELD_NUMBER = 3;
    private float exchangeRate_;
    /**
     * <pre>
     *汇率
     * </pre>
     *
     * <code>optional float exchange_rate = 3;</code>
     */
    public float getExchangeRate() {
      return exchangeRate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, curFrom_);
      }
      if (!getCurToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, curTo_);
      }
      if (exchangeRate_ != 0F) {
        output.writeFloat(3, exchangeRate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, curFrom_);
      }
      if (!getCurToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, curTo_);
      }
      if (exchangeRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, exchangeRate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adtiming.om.pb.CommonPB.Currency)) {
        return super.equals(obj);
      }
      com.adtiming.om.pb.CommonPB.Currency other = (com.adtiming.om.pb.CommonPB.Currency) obj;

      boolean result = true;
      result = result && getCurFrom()
          .equals(other.getCurFrom());
      result = result && getCurTo()
          .equals(other.getCurTo());
      result = result && (
          java.lang.Float.floatToIntBits(getExchangeRate())
          == java.lang.Float.floatToIntBits(
              other.getExchangeRate()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CUR_FROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurFrom().hashCode();
      hash = (37 * hash) + CUR_TO_FIELD_NUMBER;
      hash = (53 * hash) + getCurTo().hashCode();
      hash = (37 * hash) + EXCHANGE_RATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getExchangeRate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.CommonPB.Currency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adtiming.om.pb.CommonPB.Currency prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Currency}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Currency)
        com.adtiming.om.pb.CommonPB.CurrencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adtiming.om.pb.CommonPB.internal_static_Currency_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adtiming.om.pb.CommonPB.internal_static_Currency_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adtiming.om.pb.CommonPB.Currency.class, com.adtiming.om.pb.CommonPB.Currency.Builder.class);
      }

      // Construct using com.adtiming.om.pb.CommonPB.Currency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        curFrom_ = "";

        curTo_ = "";

        exchangeRate_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adtiming.om.pb.CommonPB.internal_static_Currency_descriptor;
      }

      public com.adtiming.om.pb.CommonPB.Currency getDefaultInstanceForType() {
        return com.adtiming.om.pb.CommonPB.Currency.getDefaultInstance();
      }

      public com.adtiming.om.pb.CommonPB.Currency build() {
        com.adtiming.om.pb.CommonPB.Currency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.adtiming.om.pb.CommonPB.Currency buildPartial() {
        com.adtiming.om.pb.CommonPB.Currency result = new com.adtiming.om.pb.CommonPB.Currency(this);
        result.curFrom_ = curFrom_;
        result.curTo_ = curTo_;
        result.exchangeRate_ = exchangeRate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adtiming.om.pb.CommonPB.Currency) {
          return mergeFrom((com.adtiming.om.pb.CommonPB.Currency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adtiming.om.pb.CommonPB.Currency other) {
        if (other == com.adtiming.om.pb.CommonPB.Currency.getDefaultInstance()) return this;
        if (!other.getCurFrom().isEmpty()) {
          curFrom_ = other.curFrom_;
          onChanged();
        }
        if (!other.getCurTo().isEmpty()) {
          curTo_ = other.curTo_;
          onChanged();
        }
        if (other.getExchangeRate() != 0F) {
          setExchangeRate(other.getExchangeRate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adtiming.om.pb.CommonPB.Currency parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adtiming.om.pb.CommonPB.Currency) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object curFrom_ = "";
      /**
       * <pre>
       *原币种
       * </pre>
       *
       * <code>optional string cur_from = 1;</code>
       */
      public java.lang.String getCurFrom() {
        java.lang.Object ref = curFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          curFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *原币种
       * </pre>
       *
       * <code>optional string cur_from = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCurFromBytes() {
        java.lang.Object ref = curFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          curFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *原币种
       * </pre>
       *
       * <code>optional string cur_from = 1;</code>
       */
      public Builder setCurFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        curFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *原币种
       * </pre>
       *
       * <code>optional string cur_from = 1;</code>
       */
      public Builder clearCurFrom() {
        
        curFrom_ = getDefaultInstance().getCurFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *原币种
       * </pre>
       *
       * <code>optional string cur_from = 1;</code>
       */
      public Builder setCurFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        curFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object curTo_ = "";
      /**
       * <pre>
       *需要转换为的币种
       * </pre>
       *
       * <code>optional string cur_to = 2;</code>
       */
      public java.lang.String getCurTo() {
        java.lang.Object ref = curTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          curTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *需要转换为的币种
       * </pre>
       *
       * <code>optional string cur_to = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCurToBytes() {
        java.lang.Object ref = curTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          curTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *需要转换为的币种
       * </pre>
       *
       * <code>optional string cur_to = 2;</code>
       */
      public Builder setCurTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        curTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *需要转换为的币种
       * </pre>
       *
       * <code>optional string cur_to = 2;</code>
       */
      public Builder clearCurTo() {
        
        curTo_ = getDefaultInstance().getCurTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *需要转换为的币种
       * </pre>
       *
       * <code>optional string cur_to = 2;</code>
       */
      public Builder setCurToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        curTo_ = value;
        onChanged();
        return this;
      }

      private float exchangeRate_ ;
      /**
       * <pre>
       *汇率
       * </pre>
       *
       * <code>optional float exchange_rate = 3;</code>
       */
      public float getExchangeRate() {
        return exchangeRate_;
      }
      /**
       * <pre>
       *汇率
       * </pre>
       *
       * <code>optional float exchange_rate = 3;</code>
       */
      public Builder setExchangeRate(float value) {
        
        exchangeRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *汇率
       * </pre>
       *
       * <code>optional float exchange_rate = 3;</code>
       */
      public Builder clearExchangeRate() {
        
        exchangeRate_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Currency)
    }

    // @@protoc_insertion_point(class_scope:Currency)
    private static final com.adtiming.om.pb.CommonPB.Currency DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adtiming.om.pb.CommonPB.Currency();
    }

    public static com.adtiming.om.pb.CommonPB.Currency getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Currency>
        PARSER = new com.google.protobuf.AbstractParser<Currency>() {
      public Currency parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Currency(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Currency> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Currency> getParserForType() {
      return PARSER;
    }

    public com.adtiming.om.pb.CommonPB.Currency getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Country_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Country_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dict_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dict_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Currency_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Currency_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\">\n\007Country\022\n\n\002a2\030\001 \001(\t\022\n\n" +
      "\002a3\030\002 \001(\t\022\n\n\002tz\030\003 \001(\005\022\017\n\007dcenter\030\004 \001(\005\"<" +
      "\n\004Dict\022\n\n\002id\030\001 \001(\005\022\013\n\003pid\030\002 \001(\005\022\014\n\004name\030" +
      "\003 \001(\t\022\r\n\005value\030\004 \001(\t\"C\n\010Currency\022\020\n\010cur_" +
      "from\030\001 \001(\t\022\016\n\006cur_to\030\002 \001(\t\022\025\n\rexchange_r" +
      "ate\030\003 \001(\002*\034\n\004Plat\022\007\n\003iOS\020\000\022\013\n\007Android\020\001*" +
      "c\n\006AdType\022\n\n\006Banner\020\000\022\n\n\006Native\020\001\022\017\n\013Rew" +
      "ardVideo\020\002\022\020\n\014Interstitial\020\003\022\n\n\006Splash\020\004" +
      "\022\022\n\016CrossPromotion\020\005* \n\006ABTest\022\010\n\004None\020\000" +
      "\022\005\n\001A\020\001\022\005\n\001B\020\002B\036\n\022com.adtiming.om.pbB\010Co",
      "mmonPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Country_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Country_descriptor,
        new java.lang.String[] { "A2", "A3", "Tz", "Dcenter", });
    internal_static_Dict_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Dict_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dict_descriptor,
        new java.lang.String[] { "Id", "Pid", "Name", "Value", });
    internal_static_Currency_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Currency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Currency_descriptor,
        new java.lang.String[] { "CurFrom", "CurTo", "ExchangeRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
