// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dev.proto

package com.adtiming.om.pb;

public final class DevPB {
  private DevPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SdkDevAppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SdkDevApp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 publisher_id = 1;</code>
     */
    int getPublisherId();

    /**
     * <code>optional int32 pub_app_id = 2;</code>
     */
    int getPubAppId();

    /**
     * <code>optional int32 adn_id = 3;</code>
     */
    int getAdnId();
  }
  /**
   * Protobuf type {@code SdkDevApp}
   */
  public  static final class SdkDevApp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SdkDevApp)
      SdkDevAppOrBuilder {
    // Use SdkDevApp.newBuilder() to construct.
    private SdkDevApp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SdkDevApp() {
      publisherId_ = 0;
      pubAppId_ = 0;
      adnId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SdkDevApp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              publisherId_ = input.readInt32();
              break;
            }
            case 16: {

              pubAppId_ = input.readInt32();
              break;
            }
            case 24: {

              adnId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adtiming.om.pb.DevPB.internal_static_SdkDevApp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adtiming.om.pb.DevPB.internal_static_SdkDevApp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adtiming.om.pb.DevPB.SdkDevApp.class, com.adtiming.om.pb.DevPB.SdkDevApp.Builder.class);
    }

    public static final int PUBLISHER_ID_FIELD_NUMBER = 1;
    private int publisherId_;
    /**
     * <code>optional int32 publisher_id = 1;</code>
     */
    public int getPublisherId() {
      return publisherId_;
    }

    public static final int PUB_APP_ID_FIELD_NUMBER = 2;
    private int pubAppId_;
    /**
     * <code>optional int32 pub_app_id = 2;</code>
     */
    public int getPubAppId() {
      return pubAppId_;
    }

    public static final int ADN_ID_FIELD_NUMBER = 3;
    private int adnId_;
    /**
     * <code>optional int32 adn_id = 3;</code>
     */
    public int getAdnId() {
      return adnId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (publisherId_ != 0) {
        output.writeInt32(1, publisherId_);
      }
      if (pubAppId_ != 0) {
        output.writeInt32(2, pubAppId_);
      }
      if (adnId_ != 0) {
        output.writeInt32(3, adnId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (publisherId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, publisherId_);
      }
      if (pubAppId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pubAppId_);
      }
      if (adnId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, adnId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adtiming.om.pb.DevPB.SdkDevApp)) {
        return super.equals(obj);
      }
      com.adtiming.om.pb.DevPB.SdkDevApp other = (com.adtiming.om.pb.DevPB.SdkDevApp) obj;

      boolean result = true;
      result = result && (getPublisherId()
          == other.getPublisherId());
      result = result && (getPubAppId()
          == other.getPubAppId());
      result = result && (getAdnId()
          == other.getAdnId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PUBLISHER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPublisherId();
      hash = (37 * hash) + PUB_APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPubAppId();
      hash = (37 * hash) + ADN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAdnId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevApp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adtiming.om.pb.DevPB.SdkDevApp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SdkDevApp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SdkDevApp)
        com.adtiming.om.pb.DevPB.SdkDevAppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adtiming.om.pb.DevPB.internal_static_SdkDevApp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adtiming.om.pb.DevPB.internal_static_SdkDevApp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adtiming.om.pb.DevPB.SdkDevApp.class, com.adtiming.om.pb.DevPB.SdkDevApp.Builder.class);
      }

      // Construct using com.adtiming.om.pb.DevPB.SdkDevApp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        publisherId_ = 0;

        pubAppId_ = 0;

        adnId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adtiming.om.pb.DevPB.internal_static_SdkDevApp_descriptor;
      }

      public com.adtiming.om.pb.DevPB.SdkDevApp getDefaultInstanceForType() {
        return com.adtiming.om.pb.DevPB.SdkDevApp.getDefaultInstance();
      }

      public com.adtiming.om.pb.DevPB.SdkDevApp build() {
        com.adtiming.om.pb.DevPB.SdkDevApp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.adtiming.om.pb.DevPB.SdkDevApp buildPartial() {
        com.adtiming.om.pb.DevPB.SdkDevApp result = new com.adtiming.om.pb.DevPB.SdkDevApp(this);
        result.publisherId_ = publisherId_;
        result.pubAppId_ = pubAppId_;
        result.adnId_ = adnId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adtiming.om.pb.DevPB.SdkDevApp) {
          return mergeFrom((com.adtiming.om.pb.DevPB.SdkDevApp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adtiming.om.pb.DevPB.SdkDevApp other) {
        if (other == com.adtiming.om.pb.DevPB.SdkDevApp.getDefaultInstance()) return this;
        if (other.getPublisherId() != 0) {
          setPublisherId(other.getPublisherId());
        }
        if (other.getPubAppId() != 0) {
          setPubAppId(other.getPubAppId());
        }
        if (other.getAdnId() != 0) {
          setAdnId(other.getAdnId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adtiming.om.pb.DevPB.SdkDevApp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adtiming.om.pb.DevPB.SdkDevApp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int publisherId_ ;
      /**
       * <code>optional int32 publisher_id = 1;</code>
       */
      public int getPublisherId() {
        return publisherId_;
      }
      /**
       * <code>optional int32 publisher_id = 1;</code>
       */
      public Builder setPublisherId(int value) {
        
        publisherId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 publisher_id = 1;</code>
       */
      public Builder clearPublisherId() {
        
        publisherId_ = 0;
        onChanged();
        return this;
      }

      private int pubAppId_ ;
      /**
       * <code>optional int32 pub_app_id = 2;</code>
       */
      public int getPubAppId() {
        return pubAppId_;
      }
      /**
       * <code>optional int32 pub_app_id = 2;</code>
       */
      public Builder setPubAppId(int value) {
        
        pubAppId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pub_app_id = 2;</code>
       */
      public Builder clearPubAppId() {
        
        pubAppId_ = 0;
        onChanged();
        return this;
      }

      private int adnId_ ;
      /**
       * <code>optional int32 adn_id = 3;</code>
       */
      public int getAdnId() {
        return adnId_;
      }
      /**
       * <code>optional int32 adn_id = 3;</code>
       */
      public Builder setAdnId(int value) {
        
        adnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 adn_id = 3;</code>
       */
      public Builder clearAdnId() {
        
        adnId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SdkDevApp)
    }

    // @@protoc_insertion_point(class_scope:SdkDevApp)
    private static final com.adtiming.om.pb.DevPB.SdkDevApp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adtiming.om.pb.DevPB.SdkDevApp();
    }

    public static com.adtiming.om.pb.DevPB.SdkDevApp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SdkDevApp>
        PARSER = new com.google.protobuf.AbstractParser<SdkDevApp>() {
      public SdkDevApp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SdkDevApp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SdkDevApp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SdkDevApp> getParserForType() {
      return PARSER;
    }

    public com.adtiming.om.pb.DevPB.SdkDevApp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SdkDevDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SdkDevDevice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 publisher_id = 1;</code>
     */
    int getPublisherId();

    /**
     * <code>optional string device_id = 2;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string device_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>optional .ABTest abt = 3;</code>
     */
    int getAbtValue();
    /**
     * <code>optional .ABTest abt = 3;</code>
     */
    com.adtiming.om.pb.CommonPB.ABTest getAbt();
  }
  /**
   * Protobuf type {@code SdkDevDevice}
   */
  public  static final class SdkDevDevice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SdkDevDevice)
      SdkDevDeviceOrBuilder {
    // Use SdkDevDevice.newBuilder() to construct.
    private SdkDevDevice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SdkDevDevice() {
      publisherId_ = 0;
      deviceId_ = "";
      abt_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SdkDevDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              publisherId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              abt_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adtiming.om.pb.DevPB.internal_static_SdkDevDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adtiming.om.pb.DevPB.internal_static_SdkDevDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adtiming.om.pb.DevPB.SdkDevDevice.class, com.adtiming.om.pb.DevPB.SdkDevDevice.Builder.class);
    }

    public static final int PUBLISHER_ID_FIELD_NUMBER = 1;
    private int publisherId_;
    /**
     * <code>optional int32 publisher_id = 1;</code>
     */
    public int getPublisherId() {
      return publisherId_;
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>optional string device_id = 2;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string device_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABT_FIELD_NUMBER = 3;
    private int abt_;
    /**
     * <code>optional .ABTest abt = 3;</code>
     */
    public int getAbtValue() {
      return abt_;
    }
    /**
     * <code>optional .ABTest abt = 3;</code>
     */
    public com.adtiming.om.pb.CommonPB.ABTest getAbt() {
      com.adtiming.om.pb.CommonPB.ABTest result = com.adtiming.om.pb.CommonPB.ABTest.valueOf(abt_);
      return result == null ? com.adtiming.om.pb.CommonPB.ABTest.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (publisherId_ != 0) {
        output.writeInt32(1, publisherId_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
      }
      if (abt_ != com.adtiming.om.pb.CommonPB.ABTest.None.getNumber()) {
        output.writeEnum(3, abt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (publisherId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, publisherId_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
      }
      if (abt_ != com.adtiming.om.pb.CommonPB.ABTest.None.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, abt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adtiming.om.pb.DevPB.SdkDevDevice)) {
        return super.equals(obj);
      }
      com.adtiming.om.pb.DevPB.SdkDevDevice other = (com.adtiming.om.pb.DevPB.SdkDevDevice) obj;

      boolean result = true;
      result = result && (getPublisherId()
          == other.getPublisherId());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && abt_ == other.abt_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PUBLISHER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPublisherId();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + ABT_FIELD_NUMBER;
      hash = (53 * hash) + abt_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adtiming.om.pb.DevPB.SdkDevDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adtiming.om.pb.DevPB.SdkDevDevice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SdkDevDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SdkDevDevice)
        com.adtiming.om.pb.DevPB.SdkDevDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adtiming.om.pb.DevPB.internal_static_SdkDevDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adtiming.om.pb.DevPB.internal_static_SdkDevDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adtiming.om.pb.DevPB.SdkDevDevice.class, com.adtiming.om.pb.DevPB.SdkDevDevice.Builder.class);
      }

      // Construct using com.adtiming.om.pb.DevPB.SdkDevDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        publisherId_ = 0;

        deviceId_ = "";

        abt_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adtiming.om.pb.DevPB.internal_static_SdkDevDevice_descriptor;
      }

      public com.adtiming.om.pb.DevPB.SdkDevDevice getDefaultInstanceForType() {
        return com.adtiming.om.pb.DevPB.SdkDevDevice.getDefaultInstance();
      }

      public com.adtiming.om.pb.DevPB.SdkDevDevice build() {
        com.adtiming.om.pb.DevPB.SdkDevDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.adtiming.om.pb.DevPB.SdkDevDevice buildPartial() {
        com.adtiming.om.pb.DevPB.SdkDevDevice result = new com.adtiming.om.pb.DevPB.SdkDevDevice(this);
        result.publisherId_ = publisherId_;
        result.deviceId_ = deviceId_;
        result.abt_ = abt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adtiming.om.pb.DevPB.SdkDevDevice) {
          return mergeFrom((com.adtiming.om.pb.DevPB.SdkDevDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adtiming.om.pb.DevPB.SdkDevDevice other) {
        if (other == com.adtiming.om.pb.DevPB.SdkDevDevice.getDefaultInstance()) return this;
        if (other.getPublisherId() != 0) {
          setPublisherId(other.getPublisherId());
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.abt_ != 0) {
          setAbtValue(other.getAbtValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adtiming.om.pb.DevPB.SdkDevDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adtiming.om.pb.DevPB.SdkDevDevice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int publisherId_ ;
      /**
       * <code>optional int32 publisher_id = 1;</code>
       */
      public int getPublisherId() {
        return publisherId_;
      }
      /**
       * <code>optional int32 publisher_id = 1;</code>
       */
      public Builder setPublisherId(int value) {
        
        publisherId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 publisher_id = 1;</code>
       */
      public Builder clearPublisherId() {
        
        publisherId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string device_id = 2;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int abt_ = 0;
      /**
       * <code>optional .ABTest abt = 3;</code>
       */
      public int getAbtValue() {
        return abt_;
      }
      /**
       * <code>optional .ABTest abt = 3;</code>
       */
      public Builder setAbtValue(int value) {
        abt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ABTest abt = 3;</code>
       */
      public com.adtiming.om.pb.CommonPB.ABTest getAbt() {
        com.adtiming.om.pb.CommonPB.ABTest result = com.adtiming.om.pb.CommonPB.ABTest.valueOf(abt_);
        return result == null ? com.adtiming.om.pb.CommonPB.ABTest.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .ABTest abt = 3;</code>
       */
      public Builder setAbt(com.adtiming.om.pb.CommonPB.ABTest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        abt_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .ABTest abt = 3;</code>
       */
      public Builder clearAbt() {
        
        abt_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SdkDevDevice)
    }

    // @@protoc_insertion_point(class_scope:SdkDevDevice)
    private static final com.adtiming.om.pb.DevPB.SdkDevDevice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adtiming.om.pb.DevPB.SdkDevDevice();
    }

    public static com.adtiming.om.pb.DevPB.SdkDevDevice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SdkDevDevice>
        PARSER = new com.google.protobuf.AbstractParser<SdkDevDevice>() {
      public SdkDevDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SdkDevDevice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SdkDevDevice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SdkDevDevice> getParserForType() {
      return PARSER;
    }

    public com.adtiming.om.pb.DevPB.SdkDevDevice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SdkDevApp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SdkDevApp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SdkDevDevice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SdkDevDevice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdev.proto\032\014common.proto\"E\n\tSdkDevApp\022\024" +
      "\n\014publisher_id\030\001 \001(\005\022\022\n\npub_app_id\030\002 \001(\005" +
      "\022\016\n\006adn_id\030\003 \001(\005\"M\n\014SdkDevDevice\022\024\n\014publ" +
      "isher_id\030\001 \001(\005\022\021\n\tdevice_id\030\002 \001(\t\022\024\n\003abt" +
      "\030\003 \001(\0162\007.ABTestB\033\n\022com.adtiming.om.pbB\005D" +
      "evPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.adtiming.om.pb.CommonPB.getDescriptor(),
        }, assigner);
    internal_static_SdkDevApp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SdkDevApp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SdkDevApp_descriptor,
        new java.lang.String[] { "PublisherId", "PubAppId", "AdnId", });
    internal_static_SdkDevDevice_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SdkDevDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SdkDevDevice_descriptor,
        new java.lang.String[] { "PublisherId", "DeviceId", "Abt", });
    com.adtiming.om.pb.CommonPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
